name: Build all packages

on:
  push:
    branches:
      - feature/deploy-pipeline-v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deployment deps
        working-directory: ./deployment/
        run: yarn


      - name: Build deployment script
        working-directory: ./deployment/
        run: yarn build


      - run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
      - uses: ./deployment/

