name: Build all packages

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install root package dependencies
        run: yarn

      - name: Install subpackages dependencies
        run: yarn bootstrap


