name: Publish all packages

on:
  push:
    branches:
      - feature/deploy-pipeline-v2

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install root package dependencies
        run: yarn

      - name: Install subpackages dependencies
        run: yarn bootstrap

      - name: Publish packages
        run: yarn publish
