name: Publish all packages

on:
  push:
    branches:
      - feature/deploy-pipeline-v2

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install root package dependencies
        run: yarn

      - name: Install subpackages dependencies
        run: yarn bootstrap

      - name: Config git email
        run: git config --global user.email "lukas.kotol@gmail.com"

      - name: Config git name
        run: git config --global user.name "Hathoriel"

      - name: Publish packages
        run: yarn publish:prerelease
