name: Deploy multiple package to NPM

on:
  push:
    branches:
      - feature/deploy-pipeline-v2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn -f
      - run: yarn lerna bootstrap
      - run: yarn lerna publish from-package --yes