name: Publish all packages

on:
  push:
    branches:
      - feature/deploy-pipeline-v2

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # 1. provide Personal Access Token for checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PAT_GITHUB }}

      # 2. setup .npmrc it uses NODE_AUTH_TOKEN
      - name: Setup .npmrc file for publish
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      # 3. configure git user used to push tag
      - name: Configure Git User
        run: |
          git config --global user.email "lukas.kotol@gmail.com"
          git config --global user.name "ci@$GITHUB_ACTOR"


      - name: Install root package dependencies
        run: yarn

      - name: Install subpackages dependencies
        run: yarn bootstrap

      - name: Publish packages
        run: yarn publish:prerelease
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

